version: 2

sources:
  - name: northwind_data
    schema: public          # ou ton schéma si tu en utilises un
    tables:
      - name: order_details
      - name: customers
      - name: products
      - name: orders
